<?php
/**
 * Hand-maintained WP asset dependency manifest for assets/js/blocks/checkout.js.
 *
 * We are not using @wordpress/scripts / Webpack, so this file substitutes for
 * what `wp-scripts build` would emit. The dependencies listed here are
 * WordPress core script handles that Woo Blocks ships on any page where the
 * Checkout block is rendered — enqueuing our bundle with these deps lets us
 * call `wc.wcBlocksRegistry.registerPaymentMethod(...)` and use wp.element.
 *
 * If/when we migrate to a build pipeline, this file will be auto-generated by
 * `@wordpress/dependency-extraction-webpack-plugin`.
 *
 * Used by Cardz3n_Gateway\Blocks_Support::get_payment_method_script_handles().
 */

return array(
	'dependencies' => array(
		'wp-element',
		'wp-html-entities',
		'wp-i18n',
		'wc-blocks-registry',
		'wc-settings',
	),
	'version'      => defined( 'CARDZ3N_GW_VERSION' ) ? CARDZ3N_GW_VERSION : '1.0.5',
);
